# Generated by Django 3.2.24 on 2025-03-19 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='driverprofile',
            unique_together={('user', 'company')},
        ),
    ]
