# Generated by Django 3.2.24 on 2025-03-19 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20250319_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_created', to='app_user.appuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='driverprofile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'company'), name='unique_driver_per_company'),
        ),
    ]
