# Generated by Django 5.1.7 on 2025-03-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_driverprofile_unique_driver_per_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=50, unique=True)),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('state_of_registration', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('operational', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_company_admin', to=settings.AUTH_USER_MODEL)),
                ('drivers', models.ManyToManyField(blank=True, related_name='vehicles', to='company.driverprofile')),
            ],
        ),
    ]
