# Generated by Django 5.1.7 on 2025-03-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER_BERTH', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty (Not Driving)')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('location', models.JSONField()),
                ('odm_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='trip.trip')),
            ],
        ),
    ]
