# Generated by Django 5.1.7 on 2025-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_triplogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplogentry',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
